// <auto-generated />
namespace ACE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Validation_check : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Validation_check));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191204235_Validation_check"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
