//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAmazingRace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<bool> ProfilePhoto { get; set; }
        public Nullable<decimal> ContactNo { get; set; }
        public string Email { get; set; }
    }
}
