//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAmazingRace
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMaster
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> StaffID { get; set; }
    }
}
